# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "config-manager solution deploy",
    is_preview=True,
)
class Deploy(AAZCommand):
    """To deploy Solution.
    """

    _aaz_info = {
        "version": "2024-08-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/Microsoft.Edge/solutionbindings/{}/deploy", "2024-08-01-preview"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, None)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )
        _args_schema.solution_name = AAZStrArg(
            options=["-n","--name","--solution-name"],
            help="The name of the Solution",
            required=True,
            # id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,24}$",
            ),
        )

        _args_schema.deployment_target = AAZStrArg(
            options=["--deployment-target-name"],
            help="The name of the Deployment Target",
            required=True,
            # id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,24}$",
            ),
        )

        # define Arg Group "Body"

        _args_schema = cls._args_schema
        _args_schema.solution_version = AAZStrArg(
            options=["-v","--version","--solution-version"],
            # arg_group="Body",
            help="Solution Version",
            required=True,
        )

        _args_schema.solution_config_version = AAZStrArg(
            options=["--solution-config-version"],
            help="Solution Binding Configuration Version",
            required=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.SolutionBindingsDeploy(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    class SolutionBindingsDeploy(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200,202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_202,
                    self.on_error,
                    lro_options={"final-state-via": "location"},
                    path_format_arguments=self.url_parameters,
                )

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Edge/solutionBindings/{solutionBindingName}/deploy",
                **self.url_parameters
            )

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "solutionBindingName",
                    str(self.ctx.args.deployment_target) + "-" + str(self.ctx.args.solution_name),
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-08-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            solution_instance_id = "/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Edge/solutionBindings/{}/solutionInstances/{}-{}".format(
                self.ctx.subscription_id,
                self.ctx.args.resource_group,
                str(self.ctx.args.deployment_target) + "-" + str(self.ctx.args.solution_name),
                str(self.ctx.args.solution_version).replace(".", "-"), 
                str(self.ctx.args.solution_config_version))
            _builder.set_const("id", solution_instance_id, AAZStrType, typ_kwargs={"flags": {"required": True}})
            bindiding_config = "/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Edge/solutionBindings/{}/solutionBindingConfigurations/{}-{}".format(
                self.ctx.subscription_id,
                self.ctx.args.resource_group,
                str(self.ctx.args.deployment_target) + "-" + str(self.ctx.args.solution_name),
                str(self.ctx.args.solution_version).replace(".", "-"),
                str(self.ctx.args.solution_config_version))
            solution_version = "/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Edge/solutions/{}/versions/{}".format(
                self.ctx.subscription_id, self.ctx.args.resource_group,
                self.ctx.args.solution_name,
                self.ctx.args.solution_version)
            _builder.set_prop("properties", AAZObjectType)
            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_const("solutionBindingConfigurationId", bindiding_config, AAZStrType,
                                     typ_kwargs={"flags": {"required": True}})
                properties.set_const("solutionVersionId", solution_version, AAZStrType,
                                     typ_kwargs={"flags": {"required": True}})
            return self.serialize_content(_content_value)
        def on_200_202(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_202
            )

        _schema_on_200_202 = None
        @classmethod
        def _build_schema_on_200_202(cls):
            if cls._schema_on_200_202 is not None:
                return cls._schema_on_200_202

            cls._schema_on_200_202 = AAZObjectType()

            _schema_on_200_202 = cls._schema_on_200_202
            _schema_on_200_202.id = AAZStrType(
                flags={"read_only": True},
            )

            _schema_on_200_202.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_202.version = AAZStrType(
                flags={"read_only": True},
            )

            _schema_on_200_202.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _schema_on_200_202.type = AAZStrType(
                flags={"read_only": True},
            )

            system_data = cls._schema_on_200_202.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
            )

            return cls._schema_on_200_202

class _DeployHelper:
    """Helper class for Deploy"""


__all__ = ["Deploy"]
