# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------
import json
import os
import platform
import subprocess
import tempfile


# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "config-manager capability-list update",
)
class Update(AAZCommand):
    """Update a Capability List Resource
    """

    _aaz_info = {
        "version": "2024-08-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/private.edge/capabilitylists/{}", "2024-08-01-preview"],
        ]
    }

    AZ_SUPPORT_GENERIC_UPDATE = True

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.capability_list_name = AAZStrArg(
            options=["-n", "--name", "--capability-list-name"],
            help="The name of the CapabilityList",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,24}$",
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        _args_schema.file = AAZStrArg(
            options=["--file"],

            help="List of capabilities",
        )

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.capabilities = AAZListArg(
            options=["--capabilities"],
            arg_group="Properties",
            help="List of capabilities",
        )

        capabilities = cls._args_schema.capabilities
        capabilities.Element = AAZObjectArg(
            nullable=True,
        )

        _element = cls._args_schema.capabilities.Element
        _element.description = AAZStrArg(
            options=["description"],
            help="Description of capability",
        )
        _element.name = AAZStrArg(
            options=["name"],
            help="Name of capability",
        )

        # define Arg Group "Resource"

        _args_schema = cls._args_schema
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="Resource",
            help="Resource tags.",
            nullable=True,
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg(
            nullable=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.CapabilityListsGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.vars.instance)
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.InstanceUpdateByGeneric(ctx=self.ctx)()
        self.post_instance_update(self.ctx.vars.instance)
        self.CapabilityListsCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class CapabilityListsGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Private.Edge/capabilityLists/{capabilityListName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "capabilityListName", self.ctx.args.capability_list_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-08-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_capability_list_read(cls._schema_on_200)

            return cls._schema_on_200

    class CapabilityListsCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200, 201]:
                return self.on_200_201(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Private.Edge/capabilityLists1/{capabilityListName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "capabilityListName", self.ctx.args.capability_list_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-08-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):

            print(str(self.ctx.args.file))
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_capability_list_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.vars.instance)

        def _update_instance(self, instance):
            payload = AAZHttpOperation.serialize_content(instance)
            payloadJson = json.dumps(payload, indent=2)
            editor = "vi"
            if platform.system() == "Windows":
                editor = "notepad"
            temp_file = tempfile.NamedTemporaryFile(delete=False)
            temp_file.write(bytes(payloadJson, "utf-8"))
            temp_file.close()
            editor_output = subprocess.run([editor, temp_file.name], capture_output=True, check=False)
            if editor_output.returncode != 0:
                os.unlink(temp_file.name)
                raise CLIInternalError("Failed to update instance")
            with open(temp_file.name, "rb") as f:
                updatedPaload = f.read().decode("utf-8")
            os.unlink(temp_file.name)
            payload_dict = json.loads(updatedPaload)
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZObjectType
            )
            _builder.set_prop("properties", AAZObjectType)
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_const("capabilities", payload_dict["properties"]["capabilities"], AAZListType, typ_kwargs={"flags": {"required": True}})

            capabilities = _builder.get(".properties.capabilities")
            if capabilities is not None:
                capabilities.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.capabilities[]")
            if _elements is not None:
                _elements.set_prop("description", AAZStrType, ".description", typ_kwargs={"flags": {"required": True}})
                _elements.set_prop("name", AAZStrType, ".name", typ_kwargs={"flags": {"required": True}})

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")
            print(AAZHttpOperation.serialize_content(_instance_value))
            return _instance_value

    class InstanceUpdateByGeneric(AAZGenericInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance_by_generic(
                self.ctx.vars.instance,
                self.ctx.generic_update_args
            )


class _UpdateHelper:
    """Helper class for Update"""

    _schema_capability_list_read = None

    @classmethod
    def _build_schema_capability_list_read(cls, _schema):
        if cls._schema_capability_list_read is not None:
            _schema.id = cls._schema_capability_list_read.id
            _schema.location = cls._schema_capability_list_read.location
            _schema.name = cls._schema_capability_list_read.name
            _schema.properties = cls._schema_capability_list_read.properties
            _schema.system_data = cls._schema_capability_list_read.system_data
            _schema.tags = cls._schema_capability_list_read.tags
            _schema.type = cls._schema_capability_list_read.type
            return

        cls._schema_capability_list_read = _schema_capability_list_read = AAZObjectType()

        capability_list_read = _schema_capability_list_read
        capability_list_read.id = AAZStrType(
            flags={"read_only": True},
        )
        capability_list_read.location = AAZStrType(
            flags={"required": True},
        )
        capability_list_read.name = AAZStrType(
            flags={"read_only": True},
        )
        capability_list_read.properties = AAZObjectType()
        capability_list_read.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        capability_list_read.tags = AAZDictType()
        capability_list_read.type = AAZStrType(
            flags={"read_only": True},
        )

        properties = _schema_capability_list_read.properties
        properties.capabilities = AAZListType(
            flags={"required": True},
        )
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
            flags={"read_only": True},
        )

        capabilities = _schema_capability_list_read.properties.capabilities
        capabilities.Element = AAZObjectType()

        _element = _schema_capability_list_read.properties.capabilities.Element
        _element.description = AAZStrType(
            flags={"required": True},
        )
        _element.name = AAZStrType(
            flags={"required": True},
        )

        system_data = _schema_capability_list_read.system_data
        system_data.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        tags = _schema_capability_list_read.tags
        tags.Element = AAZStrType()

        _schema.id = cls._schema_capability_list_read.id
        _schema.location = cls._schema_capability_list_read.location
        _schema.name = cls._schema_capability_list_read.name
        _schema.properties = cls._schema_capability_list_read.properties
        _schema.system_data = cls._schema_capability_list_read.system_data
        _schema.tags = cls._schema_capability_list_read.tags
        _schema.type = cls._schema_capability_list_read.type


__all__ = ["Update"]
