# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from knack.help_files import helps  # pylint: disable=unused-import

helps['config-manager rbac'] = """
type: group
short-summary: Used for assigning roles to principals
long-summary: Can be used for assigning a role to a principal on scopes related to deployment.          
examples:
    - name: Assign custom role b24988ac-6180-42a0-ab88-20f7382dd24c to principal 7f88d3e4-6a65-4abd-835f-548760f8b182 for deployment scope
      text: az config-manager rbac assign-for-deployment -g resource_group --deployment-target dt_id --role-id b24988ac-6180-42a0-ab88-20f7382dd24c --principal-id 7f88d3e4-6a65-4abd-835f-548760f8b182
"""

helps['config-manager rbac assign-for-deployment'] = """
type: command
short-summary: Used for assigning a role to a principal for deployment scope
long-summary: Can be used for assigning a role to a principal on scopes related to deployment           
parameters:
    - name: --deployment-target
      short-summary: name of deployment target ARM id
    - name: --role-id
      short-summary: name of role definition ARM id
    - name: --principal-id
      short-summary: name of ARM principal id
examples:
    - name: Assign custom role b24988ac-6180-42a0-ab88-20f7382dd24c to principal 7f88d3e4-6a65-4abd-835f-548760f8b182 for deployment scope
      text: az config-manager rbac assign-for-deployment -g resource_group --deployment-target dt_id --role-id b24988ac-6180-42a0-ab88-20f7382dd24c --principal-id 7f88d3e4-6a65-4abd-835f-548760f8b182
"""

helps['config-manager rbac remove-for-deployment'] = """
type: command
short-summary: Used for removing a role assigned to a principal on deployment related scopes
long-summary: Can be used for removing a role assigned to a principal on scopes related to deployment            
parameters:
    - name: --deployment-target
      short-summary: name of deployment target ARM id
    - name: --role-id
      short-summary: name of role definition ARM id
    - name: --principal-id
      short-summary: name of ARM principal id
examples:
    - name: Remove custom role b24988ac-6180-42a0-ab88-20f7382dd24c for principal 7f88d3e4-6a65-4abd-835f-548760f8b182 on deployment scope
      text: az config-manager rbac remove-for-deployment -g resource_group --deployment-target dt_id --role-id b24988ac-6180-42a0-ab88-20f7382dd24c --principal-id 7f88d3e4-6a65-4abd-835f-548760f8b182
"""