# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements

# from azure.cli.core.commands import CliCommandType
from azure.cli.core.commands import CliCommandType
from azext_config_manager._client_factory import cf_configmgr_preview

def load_command_table(self, _):
    configmanager_service_sdk = CliCommandType(
        operations_tmpl='azext_config_manager.sdk#ConfigManagerClient.{}',
        client_factory=cf_configmgr_preview)

    with self.command_group('config-manager rbak', configmanager_service_sdk, client_factory=cf_configmgr_preview) as g:
        g.custom_command('create', 'cli_cm_rbac_create')
   