# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements

from knack.log import get_logger


logger = get_logger(__name__)

def cli_cm_rbac_create(client, resource_group_name, deployment_target):

    '''Creates RBAC for Deployment'''

    client.assign_role_to_solution_bindings(resource_group_name, deployment_target)